apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudding-website
  namespace: websites-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudding-website
  template:
    metadata:
      labels:
        app: pudding-website
    spec:
      containers:
      - name: pudding-website
        image: registry.integranet.ph/websites/puddingwebsite:v.0.0.1
        ports:
        - containerPort: 80
          name: http
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pudding-website
  namespace: websites-prod
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: pudding-website
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pudding-website
  namespace: websites-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts: 
    - pudding.ws
    - www.pudding.ws
    secretName: pudding-website
  rules:
    - host: pudding.ws
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pudding-website
                port:
                  number: 80
  ingressClassName: nginx